server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/api/customers/**